import type { BudgetOption, GameEvent, Resource, Task, Vendor } from "../../types/game";

const budget = (id: string, th: string, en: string, cost: number, impactTh: string, impactEn: string, attendanceCapacity?: number): BudgetOption => ({
  id, label: { th, en }, cost, impact: { th: impactTh, en: impactEn }, attendanceCapacity,
});

const task = (id: string, th: string, en: string, effortHours: number, skills: string[], dueDay: number, cost: number, dependencies: string[], facilitatorClassification: Task["facilitatorClassification"], budgetOptions?: BudgetOption[]): Task => ({
  id, title: { th, en }, effortHours, preferredSkills: skills, dueDay, cost, dependencies,
  facilitatorClassification, status: "not_started", priority: "unassigned", priorityReason: "", issue: "", nextAction: "",
  budgetStatus: cost > 0 ? "undecided" : "included", budgetOptions, selectedBudgetOptionId: budgetOptions?.find((option) => option.cost === cost)?.id,
});

export const resources: Resource[] = [
  { id: "may", name: "May", skills: ["Project", "Coordination", "Facilitation"], dailyCapacity: 6, kind: "internal" },
  { id: "bank", name: "Bank", skills: ["Design", "Media", "Content"], dailyCapacity: 6, kind: "internal" },
  { id: "ton", name: "Ton", skills: ["IT", "Streaming", "Data"], dailyCapacity: 6, kind: "internal" },
  { id: "fon", name: "Fon", skills: ["Admin", "Procurement", "Logistics"], dailyCapacity: 6, kind: "internal" },
  { id: "ploy", name: "Ploy", skills: ["Communication", "Registration", "Content"], dailyCapacity: 6, kind: "internal" },
];

export const tasks: Task[] = [
  task("T01", "ยืนยันสถานที่จัดงาน", "Confirm Venue", 4, ["Admin", "Coordination"], 2, 0, [], "critical"),
  task("T02", "จัดทำกำหนดการหลักของงาน", "Develop Event Agenda", 6, ["Project", "Communication"], 4, 0, [], "supporting"),
  task("T03", "จัดทำร่างเนื้อหาสำหรับ CEO", "Prepare CEO Content Brief", 6, ["Project", "Content"], 3, 0, [], "critical"),
  task("T04", "ขออนุมัติเนื้อหาจาก CEO Office", "Secure CEO Content Approval", 2, ["Coordination"], 5, 0, ["T03"], "critical"),
  task("T05", "จัดทำระบบลงทะเบียน", "Set Up Registration", 6, ["Registration", "Admin"], 3, 0, [], "critical"),
  task("T06", "ส่งคำเชิญผู้เข้าร่วม", "Send Participant Invitations", 5, ["Communication"], 4, 0, ["T05"], "critical"),
  task("T07", "ออกแบบ Key Visual และ Poster", "Create Key Visual & Poster", 8, ["Design", "Media"], 4, 0, [], "supporting"),
  task("T08", "จัดทำแผนถ่ายทอดสด", "Design Livestream Plan", 8, ["IT", "Streaming"], 4, 0, ["T01"], "critical"),
  task("T09", "ทดสอบ Network และระบบ Streaming", "Conduct Network & Streaming Test", 6, ["IT", "Streaming"], 6, 0, ["T01", "T08"], "critical"),
  task("T10", "ยืนยันอาหารและเครื่องดื่ม", "Confirm Catering", 5, ["Admin", "Procurement"], 6, 42000, [], "supporting", [
    budget("expanded", "รองรับ 210 คน", "Expanded 210-person package", 58000, "รองรับ Forecast ที่เพิ่มขึ้น แต่ใช้งบสูง", "Covers the increased forecast at a higher cost.", 210),
    budget("full", "มาตรฐาน 150 คน", "Standard 150-person package", 42000, "เมนูมาตรฐานและตัวเลือกอาหารครบตาม Brief", "Standard menu and required dietary choices.", 150),
    budget("lean", "ประหยัด 130 คน", "Lean 130-person package", 34000, "รองรับ Outcome ขั้นต่ำ แต่ลดตัวเลือกอาหารและ Buffer", "Meets the minimum outcome with fewer choices and less buffer.", 130),
    budget("minimum", "ขั้นต่ำ 130 คน", "Minimum 130-person package", 28000, "อาหารรูปแบบพื้นฐาน มีความเสี่ยงต่อ Satisfaction", "Basic catering with a satisfaction risk.", 130),
  ]),
  task("T11", "ออกแบบ Innovation Workshop", "Design Innovation Workshop", 8, ["Project", "Facilitation"], 5, 0, [], "critical"),
  task("T12", "จัดเตรียมอุปกรณ์ Workshop", "Produce Workshop Materials", 6, ["Design", "Admin"], 8, 12000, ["T11"], "supporting", [
    budget("expanded", "ชุดอุปกรณ์ 210 คน", "Materials for 210", 16000, "รองรับผู้เข้าร่วมตาม Forecast ที่เพิ่มขึ้น", "Supports the increased attendance forecast.", 210),
    budget("full", "ชุดอุปกรณ์ 150 คน", "Materials for 150", 12000, "วัสดุครบสำหรับกิจกรรมตามแผน", "Complete materials for the planned workshop.", 150),
    budget("lean", "แบบประหยัด 150 คน", "Lean materials for 150", 8000, "ลดงานพิมพ์และใช้วัสดุร่วมกัน อาจทำให้กิจกรรมช้าลง", "Uses shared and reduced printed materials; facilitation may slow down.", 150),
    budget("minimum", "ขั้นต่ำ 130 คน", "Minimum materials for 130", 4000, "รองรับเพียง Outcome ขั้นต่ำและมี Buffer ต่ำ", "Supports only the minimum outcome with little buffer.", 130),
  ]),
  task("T13", "จัดเตรียมเวทีและ Backdrop", "Prepare Stage & Backdrop", 6, ["Design", "Logistics"], 8, 18000, ["T07"], "optional", [
    budget("full", "เวทีและ Backdrop เต็มรูปแบบ", "Full stage and backdrop", 18000, "ภาพลักษณ์ครบและมี Buffer งานติดตั้ง", "Full visual treatment with installation buffer."),
    budget("lean", "เวทีแบบเรียบง่าย", "Lean stage setup", 12000, "ลดองค์ประกอบตกแต่งแต่ยังส่งมอบพื้นที่หลัก", "Reduces decoration while preserving the core stage."),
    budget("minimum", "ป้ายและฉากพื้นฐาน", "Minimum signage", 6000, "เหลือเฉพาะองค์ประกอบที่จำเป็น ภาพลักษณ์ลดลง", "Keeps only essential signage with lower visual quality."),
  ]),
  task("T14", "ประสานงาน Production", "Coordinate Production Setup", 5, ["Coordination", "Logistics"], 8, 15000, ["T01"], "supporting", [
    budget("full", "ทีมประสานงานเต็มรูปแบบ", "Full production coordination", 15000, "มีคนประสานและ Buffer สำหรับแก้ปัญหาหน้างาน", "Includes coordination capacity and onsite problem-solving buffer."),
    budget("lean", "ทีมประสานงานขนาดเล็ก", "Lean coordination", 10000, "ลดคนและ Buffer ทีมภายในต้องรับงานเพิ่ม", "Reduces staffing and shifts more work to the internal team."),
    budget("minimum", "ประสานงานเฉพาะจุดสำคัญ", "Minimum coordination", 5000, "รองรับเฉพาะจุดส่งมอบหลัก มีความเสี่ยงเรื่องหน้างาน", "Covers only critical handoffs with higher delivery risk."),
  ]),
  task("T15", "จัดทำ Run of Show", "Create Run of Show", 6, ["Project", "Coordination"], 7, 0, ["T02", "T04", "T11"], "critical"),
  task("T16", "ส่ง Reminder ผู้เข้าร่วม", "Send Participant Reminder", 3, ["Communication"], 9, 0, ["T06"], "supporting"),
  task("T17", "ซ้อมใหญ่", "Full Rehearsal", 12, ["Mixed"], 9, 0, ["T04", "T09", "T15"], "critical"),
  task("T18", "จัดทำแผนสำรอง Streaming", "Create Streaming Backup Plan", 5, ["IT", "Streaming"], 8, 0, ["T08"], "supporting"),
  task("T19", "จัด Photo Booth", "Arrange Photo Booth", 6, ["Design", "Admin"], 9, 12000, [], "optional", [
    budget("full", "Photo Booth เต็มรูปแบบ", "Full photo booth", 12000, "สร้าง Engagement และภาพกิจกรรม", "Adds engagement and event imagery."),
    budget("lean", "มุมถ่ายภาพแบบง่าย", "Lean photo corner", 6000, "ลดอุปกรณ์และทีมสนับสนุน", "Uses simpler equipment and less support."),
  ]),
  task("T20", "จัดเตรียมของที่ระลึก", "Arrange Participant Gifts", 4, ["Admin", "Procurement"], 8, 15000, [], "optional", [
    budget("full", "ของที่ระลึกมาตรฐาน", "Standard participant gifts", 15000, "ของที่ระลึกครบตามจำนวนคาดการณ์", "Provides standard gifts for the expected audience."),
    budget("lean", "ของที่ระลึกแบบประหยัด", "Lean participant gifts", 8000, "ลดมูลค่าต่อชิ้นแต่ยังคงมีของที่ระลึก", "Keeps a lower-value item for participants."),
    budget("minimum", "เฉพาะรางวัลกิจกรรม", "Activity prizes only", 5000, "เปลี่ยนจากแจกทุกคนเป็นรางวัลเฉพาะกิจกรรม", "Replaces universal gifts with selected activity prizes."),
  ]),
];

const vendor = (id: string, th: string, en: string, category: string, cost: number, benefit: string, coordination: string, availability: Vendor["availability"], supportsTaskIds: string[]): Vendor => ({
  id, name: { th, en }, category, cost, benefit: { th: benefit, en: benefit }, coordination, availability,
  unlocked: availability !== "situational", planStatus: "available", supportsTaskIds,
});

export const vendors: Vendor[] = [
  vendor("V01", "สตูดิโอออกแบบ", "Design Studio", "Communication", 10000, "Design/Media 12 vendor-hours", "Bank/May 2h", "planning", ["T07", "T13", "T19"]),
  vendor("V02", "ทีมสนับสนุนงานอีเวนต์", "Event Support Crew", "Capacity", 8000, "12h during D7–D10", "1h", "later_planning", ["T12", "T13", "T14", "T17", "T20"]),
  vendor("V03", "ทีมช่วยลงทะเบียนชั่วคราว", "Temporary Registration Staff", "Capacity", 6000, "8h during D8–D10", "1h", "later_planning", []),
  vendor("V04", "ทีม Runner หน้างาน", "Event Runner Service", "Delivery", 5000, "6h during D6–D10", "1h", "later_planning", ["T10", "T12", "T13", "T14", "T17", "T20"]),
  vendor("V05", "แพ็กเกจถ่ายทอดสด", "Streaming Production Package", "Technology", 18000, "Streaming 12h + Backup Encoder", "Ton 3h", "planning", ["T08", "T09", "T18"]),
  vendor("V06", "อัปเกรด Internet", "Internet Upgrade", "Technology", 12000, "Resolve network capacity risk", "None", "situational", ["T09"]),
  vendor("V07", "ชุดอุปกรณ์ AV สำรอง", "AV Backup Kit", "Technology", 8000, "AV backup protection", "None", "situational", ["T09", "T18"]),
  vendor("V08", "ระบบลงทะเบียนสำเร็จรูป", "Registration Platform Pro", "Technology", 7000, "T05 effort 6h → 2h", "Included", "planning", ["T05"]),
  vendor("V09", "บริการช่วยสื่อสาร", "Communication Support Package", "Communication", 9000, "Communication 10 vendor-hours", "Ploy 2h", "planning", ["T02", "T03", "T06", "T16"]),
  vendor("V10", "บริการผลิตงานด่วน", "Express Print & Production", "Production", 8000, "Reduce lead time by 1 day", "None", "later_planning", ["T07", "T12", "T13", "T20"]),
  vendor("V11", "ผู้ผลิตสำรอง", "Backup Production Vendor", "Production", 14000, "Transfer delayed production", "+5,000 switching cost", "situational", ["T13", "T14"]),
  vendor("V12", "แพ็กเกจอาหารแบบยืดหยุ่น", "Flexible Catering Contract", "Flexibility", 6000, "Post-cutoff increase up to 30%", "Buy before D6", "later_planning", ["T10"]),
  vendor("V13", "ทีมสนับสนุน Workshop", "Workshop Facilitation Support", "Capacity", 9000, "Facilitation 8 vendor-hours", "May 1h", "planning", ["T11", "T12", "T17"]),
  vendor("V14", "ทีมถ่ายภาพและวิดีโอ", "Photo & Video Crew", "Production", 12000, "Photo/Video 10 vendor-hours", "1h", "later_planning", ["T19"]),
  vendor("V15", "ผู้ช่วยโครงการอิสระ", "Generalist Freelancer", "Capacity", 7000, "General 10h during D2–D9", "1h", "planning", ["T01", "T02", "T03", "T05", "T06", "T07", "T10", "T11", "T12", "T14", "T15", "T16", "T18", "T19", "T20"]),
  vendor("V16", "ผู้ประสานงานภายนอก", "Project Coordination Service", "Capacity", 9000, "Coordination 10 vendor-hours", "May 1h", "planning", ["T01", "T02", "T04", "T14", "T15", "T17"]),
];

const event = (definition: GameEvent): GameEvent => definition;
const text = (th: string, en: string) => ({ th, en });

export const events: GameEvent[] = [
  event({ code: "E01", title: text("Network รองรับไม่พอ", "Network Capacity Problem"), type: "problem", difficulty: "medium", timing: "D4–D5", deck: "core",
    announcement: text("Network ห้องประชุมยังไม่รองรับ Live Streaming อย่างเสถียร", "The venue network cannot support a stable livestream."),
    effect: text("ตั้ง Network Risk, ทำให้ T09 มีความเสี่ยง และเปิด V06/V07", "Sets network risk, puts T09 at risk, and unlocks V06/V07."), notice: text("แก้ความเสี่ยงต่อ Mission ไม่ใช่แค่อาการ", "Address the mission risk, not only the symptom."), debrief: text("ทีมแก้ที่อาการ หรือแก้ที่ความเสี่ยงต่อ Mission?", "Did the team fix the symptom or the mission risk?"),
    facilitatorGuide: { objective: text("ทดสอบ Risk response และ Contingency", "Test risk response and contingency thinking."), useWhen: text("ทีมพึ่ง Ton หรือ Streaming path เดียว", "Use when the team relies on Ton or one streaming path."), avoidWhen: text("หลีกเลี่ยงหากทีมมี Network crisis อยู่แล้ว", "Avoid when the team already has a network crisis."), watchFor: text("ทีมค้นหา Root cause, Backup และ Owner หรือไม่", "Watch for root cause, backup, and ownership."), expectedResponse: text("ประเมินผลต่อ T09/T18 จัด Capacity และเลือก Mitigation ที่คุ้มค่า", "Assess T09/T18, reallocate capacity, and choose a proportionate mitigation."), prompts: [text("ถ้า Streaming ล้ม Mission ยังสำเร็จได้หรือไม่?", "Can the mission succeed if streaming fails?"), text("ใครเป็นเจ้าของความเสี่ยงนี้?", "Who owns this risk?")], debriefConcept: text("Risk treatment: avoid, reduce, transfer, accept", "Risk treatment: avoid, reduce, transfer, accept") } }),
  event({ code: "E02", title: text("CEO เปลี่ยนวันซ้อม", "CEO Rehearsal Moved"), type: "change", difficulty: "high", timing: "D6–D7", deck: "core",
    announcement: text("CEO ซ้อมได้เฉพาะ Day 7", "The CEO can rehearse only on Day 7."), effect: text("เปลี่ยน Due By ของ T17 จาก D9 เป็น D7", "Moves T17 due date from D9 to D7."), notice: text("ตรวจ T04, T09 และ T15 ก่อนยืนยันว่าแผนยังทำได้", "Check T04, T09, and T15 before claiming the plan still works."), debrief: text("ทีมเห็น Dependency ที่กระทบตามมาหรือไม่?", "Did the team see the downstream dependencies?"),
    facilitatorGuide: { objective: text("ทดสอบ Impact analysis เมื่อ Milestone เปลี่ยน", "Test impact analysis after a milestone change."), useWhen: text("ทีมวาง Dependency และ Run of Show แล้ว", "Use after dependencies and the run of show are planned."), avoidWhen: text("อย่าใช้ก่อนทีมมี Schedule ที่พอจะถูกท้าทาย", "Avoid before the team has a schedule to challenge."), watchFor: text("ทีมแก้เฉพาะ T17 หรือย้อนดู Critical path", "Watch whether they edit only T17 or trace the critical path."), expectedResponse: text("ตรวจ T04/T09/T15, ปรับลำดับและ Capacity แล้วสื่อสารผลกระทบ", "Review T04/T09/T15, re-sequence capacity, and communicate impact."), prompts: [text("งานใดต้องเสร็จก่อนการซ้อม?", "What must finish before rehearsal?"), text("ต้อง Escalate อะไรทันที?", "What needs immediate escalation?")], debriefConcept: text("Critical path และ Change impact", "Critical path and change impact") } }),
  event({ code: "E03", title: text("งบประมาณลดลง", "Budget Reduction"), type: "change", difficulty: "high", timing: "D8–D10", deck: "core",
    announcement: text("งบสูงสุดลดจาก 120,000 เหลือ 95,000 บาท โดย Outcome หลักยังเหมือนเดิม", "The budget ceiling falls from THB 120,000 to THB 95,000 while core outcomes remain."), effect: text("วงเงินลดเหลือ 95,000 บาท ทีมสามารถลดระดับ Package ก่อนตัด Scope", "Reduces the ceiling to THB 95,000; teams can downgrade packages before cutting scope."), notice: text("ลดระดับค่าใช้จ่าย เปลี่ยน Vendor หรือตัด Optional Scope พร้อมบอกผลกระทบ", "Downgrade spend, change vendors, or cut optional scope while naming the impact."), debrief: text("ทีมลด Cost โดยรักษา Outcome อย่างไร?", "How did the team reduce cost while protecting outcomes?"),
    facilitatorGuide: { objective: text("ทดสอบ Cost–Scope–Quality trade-off", "Test cost–scope–quality trade-offs."), useWhen: text("ทีมมี Budget Plan ที่เลือก Package แล้ว", "Use after the team has selected budget packages."), avoidWhen: text("อย่าใช้พร้อม E04 หากทีมกำลัง Overload", "Avoid pairing with E04 when teams are overloaded."), watchFor: text("ทีมลดระดับรายการก่อนตัดงาน และอธิบาย Impact หรือไม่", "Watch whether teams downgrade before cutting and explain impact."), expectedResponse: text("คำนวณ Gap, ลด Package ที่กระทบ Outcome ต่ำ, ทบทวน Optional Scope และ Escalate หากจำเป็น", "Calculate the gap, downgrade low-impact packages, review optional scope, and escalate if needed."), prompts: [text("ต้องลดอีกเท่าไร และจะรักษาอะไรไว้?", "How much must be cut and what must be protected?"), text("คุณยอมรับความเสี่ยงคุณภาพข้อใด?", "Which quality risk are you accepting?")], debriefConcept: text("Value-based budgeting และ Trade-off", "Value-based budgeting and trade-offs") } }),
  event({ code: "E04", title: text("ผู้เข้าร่วมอาจเพิ่มขึ้น", "Attendance Forecast Increase"), type: "change", difficulty: "high", timing: "D8–D10", deck: "core",
    announcement: text("ผู้เข้าร่วม onsite อาจเพิ่มเป็น 210 คน", "Onsite attendance may increase to 210."), effect: text("Forecast เป็น 210 และตรวจ Package ที่รองรับคนไม่พอ", "Sets forecast to 210 and flags packages with insufficient capacity."), notice: text("ทบทวน Catering, Workshop Materials, Venue, Registration และ Staffing", "Review catering, materials, venue, registration, and staffing."), debrief: text("Change หนึ่งเรื่องกระทบกี่ส่วนของ Plan?", "How many parts of the plan did one change affect?"),
    facilitatorGuide: { objective: text("ทดสอบการมองผลกระทบข้าม Workstream", "Test cross-workstream impact thinking."), useWhen: text("ทีมมีแผน Catering และ Materials แล้ว", "Use after catering and materials are planned."), avoidWhen: text("ไม่ควรใช้พร้อม E03 หากต้องการลดความซับซ้อน", "Avoid pairing with E03 when reducing complexity."), watchFor: text("ทีมมองเฉพาะอาหารหรือเห็น Capacity, Registration และ Safety", "Watch whether they see more than catering."), expectedResponse: text("ระบุ Gap, ตัดสินใจว่าจะรองรับ Forecast หรือคง Minimum 130 พร้อมเหตุผล", "Identify gaps and decide whether to cover the forecast or protect the 130 minimum."), prompts: [text("210 คือ Commitment หรือ Forecast?", "Is 210 a commitment or a forecast?"), text("รายการใดต้องเปลี่ยนทันที รายการใดรอข้อมูลได้?", "What changes now and what can wait for data?")], debriefConcept: text("Assumption, forecast และ scalable plan", "Assumptions, forecasts, and scalable plans") } }),
  event({ code: "E05", title: text("Ton ไม่สามารถทำงานได้", "Ton Unavailable"), type: "problem", difficulty: "medium", timing: "D4–D5", deck: "core",
    announcement: text("Ton ไม่สามารถทำงานใน Day 5 ได้", "Ton is unavailable on Day 5."), effect: text("Capacity ของ Ton ใน D5 เหลือ 0 ชั่วโมง", "Sets Ton's D5 capacity to zero."), notice: text("ตรวจ Allocation conflict และ Single Point of Failure", "Check allocation conflicts and single points of failure."), debrief: text("Plan มี Single Point of Failure หรือไม่?", "Did the plan have a single point of failure?"),
    facilitatorGuide: { objective: text("ทดสอบ Resource resilience และ Skill coverage", "Test resource resilience and skill coverage."), useWhen: text("Ton มีงานสำคัญใน D5 หรือใกล้เคียง", "Use when Ton owns important work around D5."), avoidWhen: text("หลีกเลี่ยงถ้า Ton ไม่มี Allocation ที่เกี่ยวข้อง", "Avoid when Ton has no relevant allocation."), watchFor: text("ทีมย้ายชั่วโมงอย่างเดียวหรือประเมิน Skill และ Deadline ด้วย", "Watch whether they consider skills and deadlines, not just hours."), expectedResponse: text("ระบุงานกระทบ หา Backup owner, Vendor หรือปรับลำดับ", "Identify affected work and find a backup owner, vendor, or sequence."), prompts: [text("ใครทำงานนี้แทนได้จริง?", "Who can realistically take this work?"), text("การย้ายงานสร้าง Bottleneck ใหม่ตรงไหน?", "Where does reassignment create a new bottleneck?")], debriefConcept: text("Single point of failure และ cross-training", "Single points of failure and cross-training") } }),
  event({ code: "E06", title: text("Production Vendor ส่งงานช้า", "Production Vendor Delay"), type: "problem", difficulty: "medium", timing: "D6–D8", deck: "extension",
    announcement: text("งาน Stage/Backdrop จะส่งช้ากว่าแผน 2 วัน", "Stage/backdrop delivery will be two days late."), effect: text("ทำให้ T13 Delayed และเปิด V11", "Marks T13 delayed and unlocks V11."), notice: text("ใช้เมื่อทีมยังทำ T13 อยู่ และให้พิจารณาทางเลือกนอกจากรอ", "Use only when T13 is active; consider alternatives to waiting."), debrief: text("ทีมมีทางเลือกอะไรบ้างนอกจากรอ Vendor เดิม?", "What options existed besides waiting?"),
    facilitatorGuide: { objective: text("ทดสอบ Supplier risk และ Recovery options", "Test supplier risk and recovery options."), useWhen: text("T13 อยู่ใน Scope และมีผลต่อการส่งมอบ", "Use when T13 is active and relevant."), avoidWhen: text("อย่าใช้หากทีมตัด T13 แล้ว", "Do not use if T13 was dropped."), watchFor: text("ทีมเปรียบเทียบเร่งงาน เปลี่ยน Supplier ลด Scope และยอมรับความเสี่ยง", "Watch for expedite, switch, descope, and acceptance options."), expectedResponse: text("ประเมิน Switching cost, Deadline และ Minimum viable setup", "Assess switching cost, deadline, and minimum viable setup."), prompts: [text("ต้นทุนของการรอเทียบกับการเปลี่ยน Vendor คืออะไร?", "What is the cost of waiting versus switching?"), text("Minimum viable stage คืออะไร?", "What is the minimum viable stage?")], debriefConcept: text("Supplier contingency และ Recovery planning", "Supplier contingency and recovery planning") } }),
  event({ code: "E07", title: text("ข้อเสนอ Streaming Vendor", "Streaming Vendor Offer"), type: "opportunity", difficulty: "low", timing: "D1–D3", deck: "core",
    announcement: text("Vendor เสนอแพ็กเกจ Streaming ราคา 15,000 บาท จากราคาปกติ 18,000 บาท", "A vendor offers the streaming package for THB 15,000 instead of THB 18,000."), effect: text("เปิด V05 และลดราคา 3,000 บาท", "Unlocks V05 and applies a THB 3,000 discount."), notice: text("พิจารณาว่าส่วนลดนี้แก้ Bottleneck หรือเพียงดูคุ้มราคา", "Decide whether the offer solves a bottleneck or merely looks attractive."), debrief: text("เงิน 15,000 บาทซื้อ Capacity และ Risk Reduction คุ้มหรือไม่?", "Is THB 15,000 worth the capacity and risk reduction?"),
    facilitatorGuide: { objective: text("ทดสอบ Opportunity evaluation", "Test opportunity evaluation."), useWhen: text("ทีมยังตัดสินใจเรื่อง Streaming capacity", "Use while streaming capacity is still a decision."), avoidWhen: text("หลีกเลี่ยงหากทีม Commit V05 ไปแล้ว", "Avoid after V05 is already committed."), watchFor: text("ทีมซื้อเพราะลดราคา หรือผูกกับ Risk/Capacity จริง", "Watch whether they buy for the discount or for a real need."), expectedResponse: text("เทียบ Internal capacity, Network risk, Budget และ Alternative", "Compare internal capacity, network risk, budget, and alternatives."), prompts: [text("ถ้าไม่มีส่วนลด คุณยังซื้อหรือไม่?", "Would you buy without the discount?"), text("ข้อเสนอนี้ลดความเสี่ยงอะไรเป็นรูปธรรม?", "Which concrete risk does this reduce?")], debriefConcept: text("Opportunity cost และ evidence-based sourcing", "Opportunity cost and evidence-based sourcing") } }),
  event({ code: "E08", title: text("ได้คนช่วยชั่วคราว", "Extra Internal Support"), type: "opportunity", difficulty: "low", timing: "D1–D3", deck: "core",
    announcement: text("Corporate Communication ช่วยได้ 6 ชั่วโมงใน Day 6", "Corporate Communication can help for six hours on Day 6."), effect: text("เพิ่ม Resource ชั่วคราวใน D6", "Adds a temporary D6 resource."), notice: text("ใช้ Capacity กับ Bottleneck จริง ไม่ใช่กระจายงานเพราะมีคนว่าง", "Use capacity on a real bottleneck, not merely because it is available."), debrief: text("Capacity นี้มี Value กับ Bottleneck จริงหรือไม่?", "Did this capacity address a real bottleneck?"),
    facilitatorGuide: { objective: text("ทดสอบ Resource allocation ตาม Value", "Test value-based resource allocation."), useWhen: text("ทีมมี Communication/Content bottleneck", "Use when a communication or content bottleneck exists."), avoidWhen: text("หลีกเลี่ยงหากไม่มีงานที่ Skill ตรงหรือ D6 ไม่เกี่ยวข้อง", "Avoid when no matching D6 work exists."), watchFor: text("ทีมตรวจ Skill, Dependency และวันที่ก่อน Allocate", "Watch whether they check skill, dependency, and timing first."), expectedResponse: text("ใช้กับงานที่ลด Critical-path pressure หรือรักษา Outcome", "Assign it where it relieves critical-path pressure or protects outcomes."), prompts: [text("6 ชั่วโมงนี้ทำให้งานใดเสร็จเร็วขึ้นจริง?", "Which work actually finishes sooner?")], debriefConcept: text("Capacity is valuable only at the bottleneck", "Capacity is valuable only at the bottleneck") } }),
  event({ code: "E09", title: text("ยอดลงทะเบียนต่ำกว่าเป้า", "Registration Behind Target"), type: "problem", difficulty: "medium", timing: "D6", deck: "core",
    announcement: text("สิ้น Day 6 มีผู้ยืนยัน onsite เพียง 92 คน จากขั้นต่ำ 130 คน", "At the end of Day 6, only 92 onsite participants are confirmed against a minimum of 130."), effect: text("บันทึกยอดยืนยัน 92 คนและแสดง Gap 38 คน", "Records 92 confirmations and shows a 38-person gap."), notice: text("ติดตาม Outcome ไม่ใช่เพียงรายงานว่าส่ง Invitation แล้ว", "Track outcomes, not merely that invitations were sent."), debrief: text("ทีม Track Activity หรือ Track Outcome?", "Did the team track activity or outcomes?"),
    facilitatorGuide: { objective: text("ทดสอบ Outcome tracking และ Corrective action", "Test outcome tracking and corrective action."), useWhen: text("ทีมส่ง Invitation แล้วและเข้า D6", "Use after invitations and around D6."), avoidWhen: text("อย่าใช้ก่อนทีมมีโอกาสทำ T06", "Avoid before the team could reasonably complete T06."), watchFor: text("ทีมโทษกิจกรรมเดิมหรือวิเคราะห์ Conversion, Audience และ Message", "Watch for analysis of conversion, audience, and message."), expectedResponse: text("หาสาเหตุ วาง Recovery action มี Owner และ Metric ติดตาม", "Find causes and define recovery actions with an owner and metric."), prompts: [text("ต้องเพิ่มอีกกี่คนภายในกี่วัน?", "How many more confirmations are needed by when?"), text("Action ใดมีโอกาสเปลี่ยน Outcome สูงสุด?", "Which action is most likely to change the outcome?")], debriefConcept: text("Activity versus outcome metrics", "Activity versus outcome metrics") } }),
  event({ code: "E10", title: text("Catering ปิดยอด", "Catering Cut-off"), type: "problem", difficulty: "medium", timing: "D7", deck: "extension",
    announcement: text("ต้อง Final Headcount ใน Day 7 หลังจากนั้นเพิ่มได้ไม่เกิน 10%", "Final headcount is due on Day 7; later increases are limited to 10%."), effect: text("กำหนด Cut-off D7 และเพิ่มได้ 10% หรือ 30% หากมี V12", "Sets a D7 cut-off with a 10% increase limit, or 30% with V12."), notice: text("ตัดสินใจจากข้อมูลและระดับความไม่แน่นอนที่มี", "Make the commitment using available information and uncertainty."), debrief: text("ข้อมูลอะไรต้องรู้ก่อน Commit Resource?", "What information was needed before committing resources?"),
    facilitatorGuide: { objective: text("ทดสอบ Commitment under uncertainty", "Test commitment under uncertainty."), useWhen: text("ทีมมี Attendance uncertainty และเลือก Catering แล้ว", "Use when attendance is uncertain and catering is selected."), avoidWhen: text("หลีกเลี่ยงถ้าไม่ได้รวม Catering ใน Scope", "Avoid when catering is out of scope."), watchFor: text("ทีมใช้ Forecast, Minimum และ Buffer อย่างไร", "Watch how they use forecast, minimum, and buffer."), expectedResponse: text("กำหนด Headcount assumption, Contingency และ Decision owner", "Set a headcount assumption, contingency, and decision owner."), prompts: [text("คุณ Commit ตัวเลขใดและเพราะอะไร?", "Which number are you committing to and why?")], debriefConcept: text("Decision under uncertainty และ Flexibility value", "Decision-making under uncertainty and the value of flexibility") } }),
  event({ code: "E11", title: text("CEO ขอแก้เนื้อหา", "CEO Content Revision"), type: "change", difficulty: "high", timing: "D6–D8", deck: "extension",
    announcement: text("CEO Office ส่งเนื้อหากลับมาแก้ ต้องใช้เวลาเพิ่ม 3 ชั่วโมงและขออนุมัติใหม่", "The CEO Office returns the content for revision, adding three hours and requiring reapproval."), effect: text("เพิ่ม Effort T03 อีก 3 ชั่วโมง และทำให้ T04 ต้องทบทวน", "Adds three hours to T03 and puts T04 back under review."), notice: text("ตรวจผลกระทบต่อ T04, T15 และ T17 ไม่ใช่เฉพาะ T03", "Check T04, T15, and T17—not only T03."), debrief: text("ทีมปรับเฉพาะงานที่ถูกส่งกลับ หรือปรับแผนทั้งสายงาน?", "Did the team adjust only the returned work or the whole chain?"),
    facilitatorGuide: { objective: text("ทดสอบ Rework และ downstream impact", "Test rework and downstream impact."), useWhen: text("T03/T04 ถูกวางแผนหรือเสร็จแล้ว", "Use after T03/T04 are planned or completed."), avoidWhen: text("อย่าใช้ก่อนทีมเริ่มสายงาน CEO Content", "Avoid before the CEO content stream begins."), watchFor: text("ทีมเพิ่ม 3H แล้วตรวจ Dependency downstream หรือไม่", "Watch whether they trace downstream dependencies after adding the work."), expectedResponse: text("Reopen work, จัด Capacity, ทบทวน T15/T17 และ Escalate Deadline หากจำเป็น", "Reopen work, reallocate capacity, review T15/T17, and escalate if needed."), prompts: [text("Rework นี้เลื่อนงานใดตามมา?", "Which downstream work moves because of this rework?"), text("ควรเจรจาขอบเขตการแก้ไขหรือไม่?", "Should the revision scope be negotiated?")], debriefConcept: text("Rework cost และ change control", "Rework cost and change control") } }),
  event({ code: "E12", title: text("Deadline Artwork เร็วขึ้น", "Early Artwork Deadline"), type: "change", difficulty: "medium", timing: "D5–D6", deck: "extension",
    announcement: text("Final Artwork ต้องส่งไม่เกิน Day 6 ไม่เช่นนั้นไม่รับประกันการติดตั้ง", "Final artwork must be submitted by Day 6 or installation cannot be guaranteed."), effect: text("เปลี่ยน Due By ของ T13 เป็น D6", "Moves T13 due date to D6."), notice: text("ใช้เมื่อ T13 ยังอยู่ใน Scope และตรวจ Buffer ของ External Dependency", "Use when T13 is active and review external-dependency buffer."), debrief: text("ทีมเผื่อ Buffer ให้ External Dependency แค่ไหน?", "How much buffer did the team keep for external dependencies?"),
    facilitatorGuide: { objective: text("ทดสอบ Lead time และ schedule buffer", "Test lead time and schedule buffers."), useWhen: text("T13 อยู่ใน Scope และมีแผน Artwork", "Use when T13 is active and artwork is planned."), avoidWhen: text("อย่าใช้หากทีมตัด T13 แล้ว", "Do not use if T13 was dropped."), watchFor: text("ทีมเร่งงานอย่างเดียวหรือจัดการ Scope/Quality/Owner ด้วย", "Watch whether they manage scope, quality, and ownership—not only speed."), expectedResponse: text("ตรวจ T07→T13, ปรับลำดับ ลด Scope หรือใช้ V10", "Review T07→T13, re-sequence, reduce scope, or use V10."), prompts: [text("Buffer เดิมหายไปเท่าไร?", "How much buffer was lost?"), text("Minimum artwork ที่ส่งทันคืออะไร?", "What is the minimum artwork that can ship on time?")], debriefConcept: text("Lead time, buffer และ external dependency", "Lead time, buffers, and external dependencies") } }),
];

export const sponsorFacts = [
  ["Purpose / เป้าหมาย", "สร้าง employee engagement เรื่อง innovation และแนวคิดที่ต่อยอดได้"],
  ["Success / ความสำเร็จ", "Day 10, งบไม่เกินเพดาน, onsite ≥130, satisfaction ≥80%, usable ideas ≥20"],
  ["Attendance", "150 คือ forecast; 130 onsite คือ minimum; remote 3 สาขาไม่นับใน 130"],
  ["CEO", "กล่าวเปิด 15 นาที; content ที่อ้างถึง CEO ต้องอนุมัติภายใน Day 5"],
  ["Venue", "ห้องประชุมใหญ่สำนักงานใหญ่ ความจุประมาณ 220 คน"],
  ["Livestream", "ต้องถ่ายทอดสดไป 3 สาขา"],
  ["Workshop", "เป็นกิจกรรมหลักและต้องสร้างอย่างน้อย 20 usable ideas"],
  ["Food", "ต้องมี Vegetarian option"],
  ["Nice-to-have", "Photo booth, gifts และการตกแต่งเพิ่มเติม"],
];
