import { useEffect, useState } from "react";
import { events, sponsorFacts } from "../../scenarios/innovation-day/scenario";
import { loadFacilitatorState, saveFacilitatorState } from "../../app/storage";
import type { FacilitatorState, FacilitatorTeam } from "../../types/game";
import { Badge, Field, Panel, PixelButton, SaveStatus } from "../../components/ui";

const nav=["RUN","SPONSOR","APPROVAL","EVENTS","STATUS","SCORE","DEBRIEF"];
const scoreKeys=["Goal & Scope","Prioritization","Resource & Schedule","Tracking & Communication","Adaptation & Replanning"];
const debriefs=["ตอน Goal ไม่ชัด เกิดอะไรขึ้น?","Resource ตัวไหนเป็น Bottleneck?","ทีมรู้ว่า Plan มีปัญหาเมื่อไหร่?","Change ไหนทำให้ต้อง Reprioritize จริง?","มีอะไรที่ควร Escalate เร็วกว่านี้?","พรุ่งนี้เช้า คุณจะเปลี่ยนพฤติกรรมเรื่องอะไรหนึ่งอย่าง?"];
const phases=["Brief & Team Setup","Chaos Planning","Ask Sponsor + Define Mission","Priority Battle","Resource + Schedule Planning","Mission Control Simulation","Final Mission Review"];

export default function FacilitatorApp({onLock}:{onLock:()=>void}){const[state,setState]=useState<FacilitatorState>(loadFacilitatorState),[tab,setTab]=useState(0);useEffect(()=>saveFacilitatorState(state),[state]);const update=(fn:(s:FacilitatorState)=>void)=>setState(p=>{const n=structuredClone(p);fn(n);n.updatedAt=new Date().toISOString();return n});const addTeam=()=>{const name=prompt("ชื่อทีม / Team name");if(name)update(s=>s.teams.push({id:crypto.randomUUID(),name,notes:"",approvalNotes:"",planNotes:"",scores:Object.fromEntries(scoreKeys.map(k=>[k,0]))}))};return <div className="app-shell facilitator"><header className="topbar"><strong className="brand">GAME MASTER CONTROL</strong><SaveStatus timestamp={state.updatedAt}/><PixelButton variant="danger" onClick={onLock}>LOCK GAME MASTER / ล็อก</PixelButton></header><aside className="side-nav">{nav.map((x,i)=><button className={tab===i?"active":""} onClick={()=>setTab(i)} key={x}>{x}</button>)}</aside><main className="workspace"><div className="title-row"><h1>{nav[tab]}</h1><PixelButton variant="secondary" onClick={addTeam}>+ ADD TEAM</PixelButton></div>{tab===0&&<Run state={state} update={update}/>} {tab===1&&<Sponsor/>} {tab===2&&<Approval state={state} update={update}/>} {tab===3&&<Events/>} {tab===4&&<Status state={state} update={update}/>} {tab===5&&<Score state={state} update={update}/>} {tab===6&&<Debrief state={state} update={update}/>}</main></div>}
function Run({state,update}:{state:FacilitatorState;update:(fn:(s:FacilitatorState)=>void)=>void}){const[pulse,setPulse]=useState<number>();const start=()=>{if(pulse)return;setPulse(window.setInterval(()=>update(s=>s.timerSeconds++),1000))};const stop=()=>{if(pulse)clearInterval(pulse);setPulse(undefined)};return <><Panel title="CURRENT PHASE"><select value={state.currentPhase} onChange={e=>update(s=>{s.currentPhase=+e.target.value})}>{phases.map((p,i)=><option value={i} key={p}>{i}. {p}</option>)}</select><div className="timer">{String(Math.floor(state.timerSeconds/60)).padStart(2,"0")}:{String(state.timerSeconds%60).padStart(2,"0")}</div><div className="button-row"><PixelButton onClick={start}>START</PixelButton><PixelButton variant="secondary" onClick={stop}>PAUSE</PixelButton><PixelButton variant="ghost" onClick={()=>update(s=>{s.timerSeconds=0})}>RESET</PixelButton></div></Panel><Panel title="FACILITATOR WATCH"><p>มองหา assumptions, weak success definition, resource bottlenecks และ activity reports ที่ไม่พูดถึง risk/outcome</p><p className="callout">Facilitator controls pace, approvals and events. The app never replaces human facilitation.</p></Panel></>}
function Sponsor(){const[q,setQ]=useState("");return <><Field label="SEARCH / ค้นหา"><input value={q} onChange={e=>setQ(e.target.value)}/></Field>{sponsorFacts.filter(x=>x.join(" ").toLowerCase().includes(q.toLowerCase())).map(([k,v])=><Panel key={k} title={k}><p>{v}</p></Panel>)}<Panel title="REMINDER"><p>ให้ Requirement และ Outcome แต่ไม่จัด Priority แทนทีม</p></Panel></>}
function TeamPanels({state,update,field,placeholder}:{state:FacilitatorState;update:(fn:(s:FacilitatorState)=>void)=>void;field:"notes"|"approvalNotes"|"planNotes";placeholder:string}){return <>{state.teams.length===0&&<p className="empty">เพิ่มทีมเพื่อบันทึกข้อมูล / Add a team to begin.</p>}{state.teams.map(t=><Panel key={t.id} title={t.name}><textarea rows={6} placeholder={placeholder} value={t[field]} onChange={e=>update(s=>{s.teams.find(x=>x.id===t.id)![field]=e.target.value})}/></Panel>)}</>}
function Approval({state,update}:{state:FacilitatorState;update:(fn:(s:FacilitatorState)=>void)=>void}){return <><Panel title="MISSION APPROVAL CHECKLIST"><p>□ Goal clear · □ Deliverables · □ Measurable success · □ Scope · □ Stakeholders · □ Constraints · □ Facts vs assumptions</p></Panel><TeamPanels state={state} update={update} field="approvalNotes" placeholder="Verdict and conditions..."/><Panel title="PLAN REVIEW CHECKLIST"><p>□ Critical owners · □ Plausible deadlines · □ Dependencies · □ Capacity · □ Budget · □ Contingency · □ Trade-off</p></Panel><TeamPanels state={state} update={update} field="planNotes" placeholder="Bottleneck, risk, buffer and feedback..."/></>}
function Events(){const[type,setType]=useState("all");return <><div className="button-row">{["all","change","problem","opportunity"].map(x=><PixelButton variant={type===x?"primary":"ghost"} onClick={()=>setType(x)} key={x}>{x.toUpperCase()}</PixelButton>)}</div><div className="card-grid">{events.filter(e=>type==="all"||e.type===type).map(e=><Panel key={e.code} title={`${e.code} · ${e.title.th}`}><h3>{e.title.en}</h3><Badge tone={e.type==="problem"?"orange":e.type==="change"?"purple":"green"}>{e.type} · {e.difficulty} · {e.timing}</Badge><p>{e.announcement.th}</p><small>EFFECT: {e.effect.th}</small><p className="callout">{e.debrief.th}</p><PixelButton onClick={()=>navigator.clipboard?.writeText(e.code)}>COPY EVENT CODE</PixelButton></Panel>)}</div></>}
function Status({state,update}:{state:FacilitatorState;update:(fn:(s:FacilitatorState)=>void)=>void}){return <><Panel title="60-SECOND STATUS REVIEW"><ol><li>STATUS — On Track / At Risk / Critical</li><li>TOP ISSUE</li><li>IMPACT</li><li>ACTION</li><li>NEED — decision, resource or information?</li></ol><p className="callout">ผมไม่ต้องการ Activity Report — ตอนนี้ Mission มีความเสี่ยงอะไร?</p></Panel><TeamPanels state={state} update={update} field="notes" placeholder="Status, top issue, impact, action, need..."/></>}
function Score({state,update}:{state:FacilitatorState;update:(fn:(s:FacilitatorState)=>void)=>void}){return <>{state.teams.map(t=><Panel key={t.id} title={t.name}>{scoreKeys.map(k=><Field key={k} label={`${k} /20`}><input type="number" min="0" max="20" value={t.scores[k]??0} onChange={e=>update(s=>{s.teams.find(x=>x.id===t.id)!.scores[k]=Math.min(20,Math.max(0,+e.target.value))})}/></Field>)}<div className="score-total">TOTAL {Object.values(t.scores).reduce((a,b)=>a+b,0)} / 100</div></Panel>)}</>}
function Debrief({state,update}:{state:FacilitatorState;update:(fn:(s:FacilitatorState)=>void)=>void}){return <>{debriefs.map(q=><Panel key={q} action={<PixelButton variant="ghost" onClick={()=>update(s=>{s.favoriteDebriefs=s.favoriteDebriefs.includes(q)?s.favoriteDebriefs.filter(x=>x!==q):[...s.favoriteDebriefs,q]})}>{state.favoriteDebriefs.includes(q)?"★":"☆"}</PixelButton>}><p>{q}</p></Panel>)}<Panel title="TRANSFER TO REAL WORK"><p>สิ่งหนึ่งที่คุณจะเปลี่ยนในการวางแผนงานจริงพรุ่งนี้คืออะไร?</p></Panel></>}
