import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { applyEvent } from "../../engine/events";
import { getAllocatedEffort, getAvailableHours, getEffectiveEffort, getProjectedSpend, getSummary, getUnmetDependencies, getUsedHours } from "../../engine/calculations";
import { createInitialTeamState } from "../../engine/state";
import { exportTeamState, importTeamState, loadTeamState, saveTeamState } from "../../app/storage";
import { events } from "../../scenarios/innovation-day/scenario";
import type { Allocation, Decision, TeamGameState } from "../../types/game";
import { Badge, Bilingual, CapacityBar, Field, Panel, PixelButton, SaveStatus } from "../../components/ui";
import { Modal } from "../../components/Modal";

const tabs = ["MISSION", "TEAM", "CHAOS", "SPONSOR", "GOAL & SCOPE", "PRIORITY", "PLAN", "MARKET", "CONTROL", "EVENTS", "DECISIONS", "FINAL"];
const zones = [["do_first","ทำก่อน / DO FIRST"],["plan_next","วางแผนทำถัดไป / PLAN NEXT"],["delegate_outsource","มอบหมายหรือจ้าง / DELEGATE"],["defer_drop","เลื่อนหรือตัด / DEFER / DROP"]] as const;
const statuses = ["not_started","in_progress","done","at_risk","delayed","dropped"] as const;

export default function PlayerApp() {
  const navigate = useNavigate(); const [state,setState]=useState<TeamGameState>(loadTeamState); const [tab,setTab]=useState(0); const [modal,setModal]=useState<string>();
  useEffect(()=>saveTeamState(state),[state]);
  const update=(fn:(draft:TeamGameState)=>void)=>setState(prev=>{const next=structuredClone(prev);fn(next);next.updatedAt=new Date().toISOString();return next});
  const spend=getProjectedSpend(state), summary=getSummary(state);
  const advance=()=>{update(s=>{s.currentPhase=Math.max(s.currentPhase,Math.min(tab+1,11));});setTab(Math.min(tab+1,11));};
  return <div className="app-shell"><header className="topbar"><button className="brand" onClick={()=>navigate("/")}>MISSION CONTROL</button><span>TEAM: {state.teamName||"—"}</span><SaveStatus timestamp={state.updatedAt}/></header>
    <aside className="side-nav">{tabs.map((name,i)=><button key={name} className={tab===i?"active":""} disabled={i>state.currentPhase+1} onClick={()=>setTab(i)}><span>{String(i+1).padStart(2,"0")}</span>{name}</button>)}</aside>
    <main className="workspace">
      {tab===0&&<Mission state={state} update={update}/>} {tab===1&&<Team state={state}/>} {tab===2&&<Chaos state={state} update={update}/>} {tab===3&&<Sponsor state={state} update={update}/>} {tab===4&&<Goal state={state} update={update}/>} {tab===5&&<Priority state={state} update={update}/>} {tab===6&&<Plan state={state} update={update}/>} {tab===7&&<Market state={state} update={update}/>} {tab===8&&<Control state={state} update={update} summary={summary} spend={spend}/>} {tab===9&&<EventInbox state={state} setState={setState} setModal={setModal}/>} {tab===10&&<Decisions state={state} update={update}/>} {tab===11&&<Final state={state} update={update}/>} 
      {tab<11&&<div className="next-row"><PixelButton onClick={advance}>NEXT / ไปต่อ →</PixelButton></div>}
    </main>
    <footer className="hud"><span>DAY {state.currentDay} · ROUND {state.currentRound}</span><span>BUDGET {state.budgetCeiling.toLocaleString()} · PROJECTED {spend.toLocaleString()} · BUFFER {(state.budgetCeiling-spend).toLocaleString()}</span></footer>
    {modal&&<Modal title={modal} onClose={()=>setModal(undefined)}><p>บันทึกผลของเหตุการณ์แล้ว / Event effect applied and saved.</p></Modal>}
  </div>;
}

function Mission({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){return <><h1>MISSION / ภารกิจ</h1><Panel title="SCENARIO 01 — INNOVATION DAY"><div className="mission-brief"><strong>ส่งมอบ Innovation Day ภายใน 10 วันทำการ</strong><p>ผู้เข้าร่วมประมาณ 150 คน · ผู้บริหารระดับสูงเข้าร่วม · งบสูงสุด 120,000 บาท · งานจัด Day 10</p><p>Your team must deliver Innovation Day within 10 working days. Initial information is intentionally incomplete.</p></div><Field label="INSERT TEAM NAME / ชื่อทีม"><input value={state.teamName} onChange={e=>update(s=>{s.teamName=e.target.value})}/></Field></Panel></>}
function Team({state}:{state:TeamGameState}){return <><h1>YOUR TEAM / ทีมของคุณ</h1><div className="card-grid">{state.resources.filter(r=>r.kind==="internal").map((r,i)=><Panel key={r.id}><div className={`avatar a${i}`}>{r.name[0]}</div><h2>{r.name}</h2><p>{r.skills.join(" · ")}</p><CapacityBar used={0} available={6}/></Panel>)}</div></>}
function Chaos({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){return <><h1>CHAOS PLANNING</h1><p>UNDERSTAND THE WORK BEFORE PLANNING THE WORK.</p><div className="three-grid">{([["tasks","WHAT SHOULD WE DO? / เราควรทำอะไร?"],["owners","WHO MIGHT DO IT? / ใครน่าจะทำ?"],["unknowns","WHAT DO WE NEED TO KNOW? / เรายังต้องรู้อะไร?"]] as const).map(([k,l])=><Field key={k} label={l}><textarea rows={10} value={state.chaos[k]} onChange={e=>update(s=>{s.chaos[k]=e.target.value})}/></Field>)}</div></>}
function Sponsor({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){const [q,setQ]=useState("");const [a,setA]=useState("");const [kind,setKind]=useState<"fact"|"assumption"|"unknown">("unknown");const save=()=>{if(!q.trim()||!a.trim()||!state.questionTokensRemaining)return;update(s=>{s.sponsorQA.push({id:crypto.randomUUID(),question:q,answer:a,factOrAssumption:kind});s.questionTokensRemaining--});setQ("");setA("")};return <><h1>ASK SPONSOR / ถามผู้ว่าจ้าง</h1><div className="coins">QUESTION TOKENS: {Array.from({length:5},(_,i)=><span className={i<state.questionTokensRemaining?"on":"off"} key={i}>●</span>)}</div><Panel><Field label="QUESTION / คำถาม"><textarea value={q} onChange={e=>setQ(e.target.value)}/></Field><p className="callout">กรุณาถาม Facilitator โดยตรง / Please ask the Facilitator directly.</p><Field label="SPONSOR ANSWER / คำตอบ"><textarea value={a} onChange={e=>setA(e.target.value)}/></Field><Field label="FACT OR ASSUMPTION?"><select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="unknown">Unknown</option><option value="fact">Fact / ข้อมูลจริง</option><option value="assumption">Assumption / สมมติฐาน</option></select></Field><PixelButton onClick={save} disabled={!q.trim()||!a.trim()||!state.questionTokensRemaining}>SAVE Q&A / บันทึก (−1 TOKEN)</PixelButton></Panel>{state.sponsorQA.map(x=><Panel key={x.id} title={x.factOrAssumption.toUpperCase()}><strong>Q: {x.question}</strong><p>A: {x.answer}</p></Panel>)}</>}
function Goal({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){const labels={goal:"Mission Goal / เป้าหมาย",inScope:"In Scope / ในขอบเขต",outOfScope:"Out of Scope / นอกขอบเขต",deliverables:"Deliverables / สิ่งส่งมอบ",successCriteria:"Success Criteria / เกณฑ์ความสำเร็จ",stakeholders:"Stakeholders / ผู้เกี่ยวข้อง",constraints:"Constraints / ข้อจำกัด",assumptions:"Assumptions / สมมติฐาน"} as const;return <><h1>GOAL & SCOPE</h1><div className="two-grid">{Object.entries(labels).map(([k,l])=><Field key={k} label={l}><textarea value={state.missionDefinition[k as keyof typeof labels]} onChange={e=>update(s=>{s.missionDefinition[k as keyof typeof labels]=e.target.value})}/></Field>)}</div><Panel title="MISSION APPROVAL / การอนุมัติ"><select value={state.missionApproval.status} onChange={e=>update(s=>{if(e.target.value==="revise")s.missionApproval.reworkCount++;s.missionApproval.status=e.target.value as typeof s.missionApproval.status})}><option value="not_requested">Not requested</option><option value="approved">Approved / อนุมัติ</option><option value="conditional">Approved with condition</option><option value="revise">Revise / กลับไปแก้</option></select><textarea placeholder="เงื่อนไขหรือหมายเหตุ" value={state.missionApproval.notes} onChange={e=>update(s=>{s.missionApproval.notes=e.target.value})}/></Panel></>}
function Priority({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){return <><h1>PRIORITY BATTLE</h1><div className="priority-board">{zones.map(([z,label])=><Panel key={z} title={label}>{state.tasks.filter(t=>t.priorityZone===z).map(t=><TaskMini key={t.id} t={t} update={update}/>)}<select value="" onChange={e=>update(s=>{const t=s.tasks.find(x=>x.id===e.target.value);if(t)t.priorityZone=z})}><option value="">+ ADD TASK</option>{state.tasks.filter(t=>t.priorityZone!==z).map(t=><option key={t.id} value={t.id}>{t.id} {t.title.th}</option>)}</select></Panel>)}</div><Panel title="UNASSIGNED">{state.tasks.filter(t=>t.priorityZone==="unassigned").map(t=><TaskMini key={t.id} t={t} update={update}/>)}</Panel></>}
function TaskMini({t,update}:{t:TeamGameState["tasks"][number];update:(fn:(s:TeamGameState)=>void)=>void}){return <article className="task-card"><strong>{t.id} · {t.title.th}</strong><small>{t.title.en}</small><span>{t.effortHours}H · D{t.dueDay} · ฿{t.cost.toLocaleString()}</span><select value={t.priorityZone} onChange={e=>update(s=>{s.tasks.find(x=>x.id===t.id)!.priorityZone=e.target.value as typeof t.priorityZone})}><option value="unassigned">Unassigned</option>{zones.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{t.priorityZone==="do_first"&&<input placeholder="WHY IS THIS A PRIORITY?" value={t.priorityReason} onChange={e=>update(s=>{s.tasks.find(x=>x.id===t.id)!.priorityReason=e.target.value})}/>}</article>}
function Plan({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){const [taskId,setTask]=useState("T01"),[resourceId,setResource]=useState("may"),[day,setDay]=useState(1),[hours,setHours]=useState(1);const add=()=>update(s=>s.allocations.push({id:crypto.randomUUID(),taskId,resourceId,day,hours,source:"internal"}));return <><h1>RESOURCE & SCHEDULE PLAN</h1><Panel title="ADD ALLOCATION / จัดสรรชั่วโมง"><div className="allocation-form"><select value={taskId} onChange={e=>setTask(e.target.value)}>{state.tasks.map(t=><option key={t.id} value={t.id}>{t.id} {t.title.th}</option>)}</select><select value={resourceId} onChange={e=>setResource(e.target.value)}>{state.resources.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><select value={day} onChange={e=>setDay(+e.target.value)}>{Array.from({length:10},(_,i)=><option key={i} value={i+1}>Day {i+1}</option>)}</select><input type="number" min="0.5" step="0.5" value={hours} onChange={e=>setHours(+e.target.value)}/><PixelButton onClick={add}>ALLOCATE / จัดสรร</PixelButton></div></Panel><div className="schedule"><div/><>{Array.from({length:10},(_,i)=><strong key={i}>D{i+1}</strong>)}</>{state.resources.map(r=><div className="schedule-row" key={r.id}><strong>{r.name}</strong>{Array.from({length:10},(_,i)=>{const d=i+1,u=getUsedHours(state,r.id,d),a=getAvailableHours(state,r.id,d);return <CapacityBar key={d} used={u} available={a}/>})}</div>)}</div><Panel title="ALLOCATIONS">{state.allocations.map(a=><div className="list-row" key={a.id}><span>{a.taskId} · {state.resources.find(r=>r.id===a.resourceId)?.name} · D{a.day} · {a.hours}H</span><PixelButton variant="ghost" onClick={()=>update(s=>{s.allocations=s.allocations.filter(x=>x.id!==a.id)})}>REMOVE</PixelButton></div>)}</Panel></>}
function Market({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){return <><h1>VENDOR MARKETPLACE</h1><div className="card-grid">{state.vendors.filter(v=>v.unlocked).map(v=><Panel key={v.id} title={`${v.id} · ${v.category}`}><h2><Bilingual {...v.name}/></h2><strong>฿{v.cost.toLocaleString()}</strong><p>{v.benefit.th}</p><small>COORDINATION: {v.coordination}</small><PixelButton disabled={v.hired} onClick={()=>{if(confirm(`ยืนยันจ้าง ${v.name.th}?`))update(s=>{s.vendors.find(x=>x.id===v.id)!.hired=true;if(v.id==="V06")s.networkRisk=false;if(v.id==="V12"&&s.cateringCutoffDay)s.postCutoffIncreaseLimit=.3})}}>{v.hired?"COMMITTED / จ้างแล้ว":"HIRE / จ้าง"}</PixelButton></Panel>)}</div></>}
function Control({state,update,summary,spend}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void;summary:ReturnType<typeof getSummary>;spend:number}){return <><h1>MISSION CONTROL</h1><div className="stats">{Object.entries(summary).map(([k,v])=><Panel key={k}><strong>{v}</strong><span>{k}</span></Panel>)}<Panel><strong className={spend>state.budgetCeiling?"warning":""}>{(state.budgetCeiling-spend).toLocaleString()}</strong><span>Budget Remaining</span></Panel></div><Field label="MISSION STATUS"><select value={state.missionStatus} onChange={e=>update(s=>{s.missionStatus=e.target.value as typeof s.missionStatus})}><option value="on_track">ON TRACK</option><option value="at_risk">AT RISK</option><option value="critical">CRITICAL</option></select></Field>{state.tasks.map(t=>{const unmet=getUnmetDependencies(state,t.id),eff=getEffectiveEffort(state,t.id),alloc=getAllocatedEffort(state,t.id);return <article className="tracking-row" key={t.id}><strong>{t.id}</strong><span><Bilingual {...t.title}/></span><span>{alloc}/{eff}H · D{t.dueDay}</span>{unmet.length>0&&<Badge tone="orange">DEPENDENCY: {unmet.join(", ")}</Badge>}<select value={t.status} onChange={e=>update(s=>{s.tasks.find(x=>x.id===t.id)!.status=e.target.value as typeof t.status})}>{statuses.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Issue / ประเด็น" value={t.issue} onChange={e=>update(s=>{s.tasks.find(x=>x.id===t.id)!.issue=e.target.value})}/><input placeholder="Next action" value={t.nextAction} onChange={e=>update(s=>{s.tasks.find(x=>x.id===t.id)!.nextAction=e.target.value})}/></article>})}</>}
function EventInbox({state,setState,setModal}:{state:TeamGameState;setState:React.Dispatch<React.SetStateAction<TeamGameState>>;setModal:(x:string)=>void}){const [code,setCode]=useState(""),[msg,setMsg]=useState("");const submit=()=>{const result=applyEvent(state,code);if(result.error){setMsg(result.error==="invalid"?"ไม่พบรหัส / Invalid code":"ใช้เหตุการณ์นี้แล้ว / Already applied");return}setState(result.state);const e=events.find(x=>x.code===code.toUpperCase());setModal(`${e?.code} — ${e?.title.th} / ${e?.title.en}`);setMsg("");setCode("")};return <><h1>EVENT INBOX / รับเหตุการณ์</h1><Panel><div className="event-entry"><input placeholder="E03" value={code} maxLength={3} onChange={e=>setCode(e.target.value.toUpperCase())}/><PixelButton onClick={submit}>RECEIVE EVENT / รับเหตุการณ์</PixelButton></div>{msg&&<p className="warning">{msg}</p>}</Panel>{state.appliedEventCodes.map(c=>{const e=events.find(x=>x.code===c)!;return <Panel key={c} title={`${c} · ${e.title.th} / ${e.title.en}`}><p>{e.announcement.th}</p><p>{e.announcement.en}</p><Badge tone="purple">{e.type.toUpperCase()}</Badge></Panel>})}</>}
function Decisions({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){const empty={situation:"",recommendation:"",impact:"",decisionNeeded:"",sponsorResponse:"",notes:""};const [form,setForm]=useState(empty);const save=()=>{if(!form.situation)return;update(s=>s.decisions.push({...form,id:crypto.randomUUID(),day:s.currentDay,createdAt:new Date().toISOString()} as Decision));setForm(empty)};return <><h1>DECISION REQUEST / ขอการตัดสินใจ</h1><Panel><div className="two-grid">{Object.keys(empty).map(k=><Field key={k} label={k.replace(/[A-Z]/g,m=>` ${m}`).toUpperCase()}><textarea value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})}/></Field>)}</div><PixelButton onClick={save}>REQUEST DECISION / บันทึก</PixelButton></Panel>{state.decisions.map(d=><Panel key={d.id} title={`DAY ${d.day} · ${d.sponsorResponse||"PENDING"}`}><strong>{d.situation}</strong><p>RECOMMENDATION: {d.recommendation}</p></Panel>)}</>}
function Final({state,update}:{state:TeamGameState;update:(fn:(s:TeamGameState)=>void)=>void}){const labels={missionResult:"Mission Result / ผลภารกิจ",delivered:"Delivered / ส่งมอบแล้ว",notDelivered:"Not Delivered / ยังไม่ส่งมอบ",biggestDecision:"Biggest Decision",biggestRisk:"Biggest Risk",doDifferently:"What We Would Do Differently"} as const;const [error,setError]=useState("");return <><h1>FINAL MISSION REVIEW</h1><Panel>{Object.entries(labels).map(([k,l])=><Field key={k} label={l}><textarea disabled={state.finalReview.locked} value={state.finalReview[k as keyof typeof labels] as string} onChange={e=>update(s=>{(s.finalReview[k as keyof typeof labels] as string)=e.target.value})}/></Field>)}<div className="button-row"><PixelButton disabled={state.finalReview.locked} onClick={()=>update(s=>{s.finalReview.locked=true})}>LOCK FINAL REVIEW / ยืนยัน</PixelButton><PixelButton variant="secondary" onClick={()=>exportTeamState(state)}>EXPORT JSON</PixelButton><label className="pixel-button ghost">IMPORT JSON<input hidden type="file" accept="application/json" onChange={async e=>{try{const f=e.target.files?.[0];if(f)setStateAwait(await importTeamState(f),update)}catch{setError("ไฟล์ไม่ถูกต้อง / Invalid file")}}}/></label></div>{error&&<p className="warning">{error}</p>}</Panel></>}
function setStateAwait(next:TeamGameState,update:(fn:(s:TeamGameState)=>void)=>void){update(s=>Object.assign(s,next))}
